up=keyboard,273
down=keyboard,274
left=keyboard,276
right=keyboard,275
confirm=keyboard,292
cancel=keyboard,285
menu=keyboard,293
settings=keyboard,13
manual=keyboard,282
modifier=keyboard,304
section_prev=keyboard,9
section_next=keyboard,8
pageup=keyboard,9
pagedown=keyboard,8
